// Copyright 2013 Joseph Hager. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package eng

import (
	"github.com/go-gl/glfw"
)

// Keyboard key constants.
type Key int

var (
	Escape     = Key(glfw.KeyEsc)
	F1         = Key(glfw.KeyF1)
	F2         = Key(glfw.KeyF2)
	F3         = Key(glfw.KeyF3)
	F4         = Key(glfw.KeyF4)
	F5         = Key(glfw.KeyF5)
	F6         = Key(glfw.KeyF6)
	F7         = Key(glfw.KeyF7)
	F8         = Key(glfw.KeyF8)
	F9         = Key(glfw.KeyF9)
	F10        = Key(glfw.KeyF10)
	F11        = Key(glfw.KeyF11)
	F12        = Key(glfw.KeyF12)
	F13        = Key(glfw.KeyF13)
	F14        = Key(glfw.KeyF14)
	F15        = Key(glfw.KeyF15)
	F16        = Key(glfw.KeyF16)
	F17        = Key(glfw.KeyF17)
	F18        = Key(glfw.KeyF18)
	F19        = Key(glfw.KeyF19)
	F20        = Key(glfw.KeyF20)
	F21        = Key(glfw.KeyF21)
	F22        = Key(glfw.KeyF22)
	F23        = Key(glfw.KeyF23)
	F24        = Key(glfw.KeyF24)
	F25        = Key(glfw.KeyF25)
	Up         = Key(glfw.KeyUp)
	Down       = Key(glfw.KeyDown)
	Left       = Key(glfw.KeyLeft)
	Right      = Key(glfw.KeyRight)
	Lshift     = Key(glfw.KeyLshift)
	Rshift     = Key(glfw.KeyRshift)
	Lctrl      = Key(glfw.KeyLctrl)
	Rctrl      = Key(glfw.KeyRctrl)
	Lalt       = Key(glfw.KeyLalt)
	Ralt       = Key(glfw.KeyRalt)
	Tab        = Key(glfw.KeyTab)
	Space      = Key(glfw.KeySpace)
	Enter      = Key(glfw.KeyEnter)
	Backspace  = Key(glfw.KeyBackspace)
	Insert     = Key(glfw.KeyInsert)
	Del        = Key(glfw.KeyDel)
	Pageup     = Key(glfw.KeyPageup)
	Pagedown   = Key(glfw.KeyPagedown)
	Home       = Key(glfw.KeyHome)
	End        = Key(glfw.KeyEnd)
	KP0        = Key(glfw.KeyKP0)
	KP1        = Key(glfw.KeyKP1)
	KP2        = Key(glfw.KeyKP2)
	KP3        = Key(glfw.KeyKP3)
	KP4        = Key(glfw.KeyKP4)
	KP5        = Key(glfw.KeyKP5)
	KP6        = Key(glfw.KeyKP6)
	KP7        = Key(glfw.KeyKP7)
	KP8        = Key(glfw.KeyKP8)
	KP9        = Key(glfw.KeyKP9)
	KPDivide   = Key(glfw.KeyKPDivide)
	KPMultiply = Key(glfw.KeyKPMultiply)
	KPSubtract = Key(glfw.KeyKPSubtract)
	KPAdd      = Key(glfw.KeyKPAdd)
	KPDecimal  = Key(glfw.KeyKPDecimal)
	KPEqual    = Key(glfw.KeyKPEqual)
	KPEnter    = Key(glfw.KeyKPEnter)
	KPNumlock  = Key(glfw.KeyKPNumlock)
	Capslock   = Key(glfw.KeyCapslock)
	Scrolllock = Key(glfw.KeyScrolllock)
	Pause      = Key(glfw.KeyPause)
	Lsuper     = Key(glfw.KeyLsuper)
	Rsuper     = Key(glfw.KeyRsuper)
	Menu       = Key(glfw.KeyMenu)
)

// Mouse button constants.
type Button int

var (
	Mouse1      = Button(glfw.Mouse1)
	Mouse2      = Button(glfw.Mouse2)
	Mouse3      = Button(glfw.Mouse3)
	Mouse4      = Button(glfw.Mouse4)
	Mouse5      = Button(glfw.Mouse5)
	Mouse6      = Button(glfw.Mouse6)
	Mouse7      = Button(glfw.Mouse7)
	Mouse8      = Button(glfw.Mouse8)
	MouseLeft   = Button(glfw.MouseLeft)
	MouseRight  = Button(glfw.MouseRight)
	MouseMiddle = Button(glfw.MouseMiddle)
)
