//+build !netgo,!android

package act

import "github.com/go-gl/glfw/v3.1/glfw"

const (
	KeyUnknown      = KeyCode | Code(glfw.KeyUnknown)
	KeySpace        = KeyCode | Code(glfw.KeySpace)
	KeyApostrophe   = KeyCode | Code(glfw.KeyApostrophe)
	KeyComma        = KeyCode | Code(glfw.KeyComma)
	KeyMinus        = KeyCode | Code(glfw.KeyMinus)
	KeyPeriod       = KeyCode | Code(glfw.KeyPeriod)
	KeySlash        = KeyCode | Code(glfw.KeySlash)
	Key0            = KeyCode | Code(glfw.Key0)
	Key1            = KeyCode | Code(glfw.Key1)
	Key2            = KeyCode | Code(glfw.Key2)
	Key3            = KeyCode | Code(glfw.Key3)
	Key4            = KeyCode | Code(glfw.Key4)
	Key5            = KeyCode | Code(glfw.Key5)
	Key6            = KeyCode | Code(glfw.Key6)
	Key7            = KeyCode | Code(glfw.Key7)
	Key8            = KeyCode | Code(glfw.Key8)
	Key9            = KeyCode | Code(glfw.Key9)
	KeySemicolon    = KeyCode | Code(glfw.KeySemicolon)
	KeyEqual        = KeyCode | Code(glfw.KeyEqual)
	KeyA            = KeyCode | Code(glfw.KeyA)
	KeyB            = KeyCode | Code(glfw.KeyB)
	KeyC            = KeyCode | Code(glfw.KeyC)
	KeyD            = KeyCode | Code(glfw.KeyD)
	KeyE            = KeyCode | Code(glfw.KeyE)
	KeyF            = KeyCode | Code(glfw.KeyF)
	KeyG            = KeyCode | Code(glfw.KeyG)
	KeyH            = KeyCode | Code(glfw.KeyH)
	KeyI            = KeyCode | Code(glfw.KeyI)
	KeyJ            = KeyCode | Code(glfw.KeyJ)
	KeyK            = KeyCode | Code(glfw.KeyK)
	KeyL            = KeyCode | Code(glfw.KeyL)
	KeyM            = KeyCode | Code(glfw.KeyM)
	KeyN            = KeyCode | Code(glfw.KeyN)
	KeyO            = KeyCode | Code(glfw.KeyO)
	KeyP            = KeyCode | Code(glfw.KeyP)
	KeyQ            = KeyCode | Code(glfw.KeyQ)
	KeyR            = KeyCode | Code(glfw.KeyR)
	KeyS            = KeyCode | Code(glfw.KeyS)
	KeyT            = KeyCode | Code(glfw.KeyT)
	KeyU            = KeyCode | Code(glfw.KeyU)
	KeyV            = KeyCode | Code(glfw.KeyV)
	KeyW            = KeyCode | Code(glfw.KeyW)
	KeyX            = KeyCode | Code(glfw.KeyX)
	KeyY            = KeyCode | Code(glfw.KeyY)
	KeyZ            = KeyCode | Code(glfw.KeyZ)
	KeyLeftBracket  = KeyCode | Code(glfw.KeyLeftBracket)
	KeyBackslash    = KeyCode | Code(glfw.KeyBackslash)
	KeyRightBracket = KeyCode | Code(glfw.KeyRightBracket)
	KeyGraveAccent  = KeyCode | Code(glfw.KeyGraveAccent)
	KeyWorld1       = KeyCode | Code(glfw.KeyWorld1)
	KeyWorld2       = KeyCode | Code(glfw.KeyWorld2)
	KeyEscape       = KeyCode | Code(glfw.KeyEscape)
	KeyEnter        = KeyCode | Code(glfw.KeyEnter)
	KeyTab          = KeyCode | Code(glfw.KeyTab)
	KeyBackspace    = KeyCode | Code(glfw.KeyBackspace)
	KeyInsert       = KeyCode | Code(glfw.KeyInsert)
	KeyDelete       = KeyCode | Code(glfw.KeyDelete)
	KeyRight        = KeyCode | Code(glfw.KeyRight)
	KeyLeft         = KeyCode | Code(glfw.KeyLeft)
	KeyDown         = KeyCode | Code(glfw.KeyDown)
	KeyUp           = KeyCode | Code(glfw.KeyUp)
	KeyPageUp       = KeyCode | Code(glfw.KeyPageUp)
	KeyPageDown     = KeyCode | Code(glfw.KeyPageDown)
	KeyHome         = KeyCode | Code(glfw.KeyHome)
	KeyEnd          = KeyCode | Code(glfw.KeyEnd)
	KeyCapsLock     = KeyCode | Code(glfw.KeyCapsLock)
	KeyScrollLock   = KeyCode | Code(glfw.KeyScrollLock)
	KeyNumLock      = KeyCode | Code(glfw.KeyNumLock)
	KeyPrintScreen  = KeyCode | Code(glfw.KeyPrintScreen)
	KeyPause        = KeyCode | Code(glfw.KeyPause)
	KeyF1           = KeyCode | Code(glfw.KeyF1)
	KeyF2           = KeyCode | Code(glfw.KeyF2)
	KeyF3           = KeyCode | Code(glfw.KeyF3)
	KeyF4           = KeyCode | Code(glfw.KeyF4)
	KeyF5           = KeyCode | Code(glfw.KeyF5)
	KeyF6           = KeyCode | Code(glfw.KeyF6)
	KeyF7           = KeyCode | Code(glfw.KeyF7)
	KeyF8           = KeyCode | Code(glfw.KeyF8)
	KeyF9           = KeyCode | Code(glfw.KeyF9)
	KeyF10          = KeyCode | Code(glfw.KeyF10)
	KeyF11          = KeyCode | Code(glfw.KeyF11)
	KeyF12          = KeyCode | Code(glfw.KeyF12)
	KeyF13          = KeyCode | Code(glfw.KeyF13)
	KeyF14          = KeyCode | Code(glfw.KeyF14)
	KeyF15          = KeyCode | Code(glfw.KeyF15)
	KeyF16          = KeyCode | Code(glfw.KeyF16)
	KeyF17          = KeyCode | Code(glfw.KeyF17)
	KeyF18          = KeyCode | Code(glfw.KeyF18)
	KeyF19          = KeyCode | Code(glfw.KeyF19)
	KeyF20          = KeyCode | Code(glfw.KeyF20)
	KeyF21          = KeyCode | Code(glfw.KeyF21)
	KeyF22          = KeyCode | Code(glfw.KeyF22)
	KeyF23          = KeyCode | Code(glfw.KeyF23)
	KeyF24          = KeyCode | Code(glfw.KeyF24)
	KeyF25          = KeyCode | Code(glfw.KeyF25)
	KeyPad0         = KeyCode | Code(glfw.KeyKP0)
	KeyPad1         = KeyCode | Code(glfw.KeyKP1)
	KeyPad2         = KeyCode | Code(glfw.KeyKP2)
	KeyPad3         = KeyCode | Code(glfw.KeyKP3)
	KeyPad4         = KeyCode | Code(glfw.KeyKP4)
	KeyPad5         = KeyCode | Code(glfw.KeyKP5)
	KeyPad6         = KeyCode | Code(glfw.KeyKP6)
	KeyPad7         = KeyCode | Code(glfw.KeyKP7)
	KeyPad8         = KeyCode | Code(glfw.KeyKP8)
	KeyPad9         = KeyCode | Code(glfw.KeyKP9)
	KeyPadDecimal   = KeyCode | Code(glfw.KeyKPDecimal)
	KeyPadDivide    = KeyCode | Code(glfw.KeyKPDivide)
	KeyPadMultiply  = KeyCode | Code(glfw.KeyKPMultiply)
	KeyPadSubtract  = KeyCode | Code(glfw.KeyKPSubtract)
	KeyPadAdd       = KeyCode | Code(glfw.KeyKPAdd)
	KeyPadEnter     = KeyCode | Code(glfw.KeyKPEnter)
	KeyPadEqual     = KeyCode | Code(glfw.KeyKPEqual)
	KeyLeftShift    = KeyCode | Code(glfw.KeyLeftShift)
	KeyLeftControl  = KeyCode | Code(glfw.KeyLeftControl)
	KeyLeftAlt      = KeyCode | Code(glfw.KeyLeftAlt)
	KeyLeftSuper    = KeyCode | Code(glfw.KeyLeftSuper)
	KeyRightShift   = KeyCode | Code(glfw.KeyRightShift)
	KeyRightControl = KeyCode | Code(glfw.KeyRightControl)
	KeyRightAlt     = KeyCode | Code(glfw.KeyRightAlt)
	KeyRightSuper   = KeyCode | Code(glfw.KeyRightSuper)
	KeyMenu         = KeyCode | Code(glfw.KeyMenu)
)

const (
	Mouse1 = MouseCode | Code(glfw.MouseButton1)
	Mouse2 = MouseCode | Code(glfw.MouseButton2)
	Mouse3 = MouseCode | Code(glfw.MouseButton3)
	Mouse4 = MouseCode | Code(glfw.MouseButton4)
	Mouse5 = MouseCode | Code(glfw.MouseButton5)
	Mouse6 = MouseCode | Code(glfw.MouseButton6)
	Mouse7 = MouseCode | Code(glfw.MouseButton7)
	Mouse8 = MouseCode | Code(glfw.MouseButton8)
)

const (
	MouseLeft   = MouseCode | Code(glfw.MouseButton1)
	MouseRight  = MouseCode | Code(glfw.MouseButton2)
	MouseMiddle = MouseCode | Code(glfw.MouseButton3)
)
